### ISSUE TITLE
Keep track with latest SMTP 7.x-1.7 version in D7

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/smtp#11]
**Changes since 7.x-1.3**

- [x] Removes SendmailSend() from smtp.phpmailier
- [x] <a href="https://www.drupal.org/project/smtp/issues/2724331">#2724331</a> by <a href='/u/jeffm2001'>JeffM2001</a>, <a href='/u/dang42'>dang42</a>: "From Name" no longer works in v1.4
- [x] <a href="https://www.drupal.org/project/smtp/issues/2720015">#2720015</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/hossein425'>hossein425</a>, <a href='/u/wundo'>wundo</a>, <a href='/u/rcodina'>rcodina</a>, <a href='/u/vitalblue'>vitalblue</a>, <a href='/u/ptmkenny'>ptmkenny</a>, <a href='/u/ehj-52n'>ehj-52n</a>: Fatal error when sending emails
- [x] <a href="https://www.drupal.org/project/smtp/issues/2226483">#2226483</a> by <a href='/u/bago'>bago</a>, <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/wundo'>wundo</a>: Backup configuration doesn't work (bundled PHPmailer issue)
- [x] <a href="https://www.drupal.org/project/smtp/issues/2299479">#2299479</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/ben_chad'>ben_chad</a>, <a href='/u/jordanpagewhite'>jordanpagewhite</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/wundo'>wundo</a>: Use form submit handler to send test email
- [x] <a href="https://www.drupal.org/project/smtp/issues/1847678">#1847678</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/wundo'>wundo</a>, <a href='/u/matthiasm11'>matthiasm11</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/gadaniels72'>gadaniels72</a>, <a href='/u/janton'>janton</a>: SMTP server failure, no retry?
- [x] <a href="https://www.drupal.org/project/smtp/issues/2651398">#2651398</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/gadaniels72'>gadaniels72</a>, <a href='/u/jordanpagewhite'>jordanpagewhite</a>, <a href='/u/wundo'>wundo</a>: Add option to reroute all email to a single address
- [x] <a href="https://www.drupal.org/project/smtp/issues/2670760">#2670760</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/nancydru'>NancyDru</a>: Please remove Hook_update_N() from update doc
- [x] <a href="https://www.drupal.org/project/smtp/issues/2720015">#2720015</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/rcodina'>rcodina</a>: Fatal error when sending emails
- [x] <a href="https://www.drupal.org/project/smtp/issues/2716985">#2716985</a> by <a href='/u/jenlampton'>jenlampton</a>, <a href='/u/wundo'>wundo</a>: Check for dblog module (and access?) before providing link
- [x] <a href="https://www.drupal.org/project/smtp/issues/2653398">#2653398</a> by <a href='/u/wundo'>wundo</a>: Using the TRUE/FALSE instead of 0/1 on form builder
- [x] <a href="https://www.drupal.org/project/smtp/issues/2653398">#2653398</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>: Add option to not actually deliver emails
- [x] <a href="https://www.drupal.org/project/smtp/issues/2698029">#2698029</a> by <a href='/u/wundo'>wundo</a>: Fixes watchdog not being logged for messages which skips the queue
- [x] <a href="https://www.drupal.org/project/smtp/issues/2656510">#2656510</a> by <a href='/u/arnested'>arnested</a>, <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/estoyausente'>estoyausente</a>: Make hostname and HELO configurable
- [x] <a href="https://www.drupal.org/project/smtp/issues/2556369">#2556369</a> by <a href='/u/jurgenhaas'>jurgenhaas</a>, <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/wundo'>wundo</a>: Whitespace in header values could break functionality
- [x] <a href="https://www.drupal.org/project/smtp/issues/1953134">#1953134</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/gadaniels72'>gadaniels72</a>, <a href='/u/wundo'>wundo</a>: Use autocomplete="off" attribut for SMTP Authentication fields
- [x] <a href="https://www.drupal.org/project/smtp/issues/2274571">#2274571</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/jaypan'>Jaypan</a>: Implement hook_variable_info
- [x] <a href="https://www.drupal.org/project/smtp/issues/2701263">#2701263</a> by <a href='/u/tcarmona'>tcarmona</a>: Typo inside the SMTP server address error
- [x] <a href="https://www.drupal.org/project/smtp/issues/2701267">#2701267</a> by <a href='/u/tcarmona'>tcarmona</a>: Typo inside the SMTP port number error
- [x] <a href="https://www.drupal.org/project/smtp/issues/2701203">#2701203</a> by <a href='/u/tcarmona'>tcarmona</a>: Typo inside the SSL description
- [x] <a href="https://www.drupal.org/project/smtp/issues/2681999">#2681999</a> by <a href='/u/tuwebo'>TuWebO</a>, <a href='/u/dineshw'>dineshw</a>, <a href='/u/wundo'>wundo</a>, <a href='/u/nidhi.badani'>nidhi.badani</a>: SMTP Error: Invalid address, but address not shown in watchdog
- [x] <a href="https://www.drupal.org/project/smtp/issues/2596413">#2596413</a> by <a href='/u/ivanstegic'>ivanstegic</a>, <a href='/u/sammuell'>sammuell</a>, <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/wundo'>wundo</a>: From header is not correctly handled
- [x] <a href="https://www.drupal.org/project/smtp/issues/2653394">#2653394</a>: Adding missing files
- [x] <a href="https://www.drupal.org/project/smtp/issues/2653394">#2653394</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/jordanpagewhite'>jordanpagewhite</a>: Integration with Maillog
- [x] <a href="https://www.drupal.org/project/smtp/issues/2497359">#2497359</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/jrreid'>jrreid</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/gadaniels72'>gadaniels72</a>, <a href='/u/wundo'>wundo</a>: For debugging, use drupal_set_message instead of printing directly to the output
- [x] <a href="https://www.drupal.org/project/smtp/issues/1889278">#1889278</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/simon-georges'>Simon Georges</a>: Remove smtp_library variable from 7.x-version
- [x] <a href="https://www.drupal.org/project/smtp/issues/2651406">#2651406</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/alex_drupal_dev'>alex_drupal_dev</a>, <a href='/u/gadaniels72'>gadaniels72</a>: Incorrect variable used when logging all messages
- [x] <a href="https://www.drupal.org/project/smtp/issues/2309875">#2309875</a> by <a href='/u/cobadger'>COBadger</a>, <a href='/u/damienmckenna'>DamienMcKenna</a>: Error in 'from' using site-wide contact form and multiple recipients
- [x] <a href="https://www.drupal.org/project/smtp/issues/2548133">#2548133</a> by <a href='/u/rrfegade'>rrfegade</a>, <a href='/u/damienmckenna'>DamienMcKenna</a>, <a href='/u/wundo'>wundo</a>: Remove unused varibles from D7
- [x] <a href="https://www.drupal.org/project/smtp/issues/2653386">#2653386</a> by <a href='/u/damienmckenna'>DamienMcKenna</a>: Add some tests

**Comment by jenlampton** [comment]
There were a lot of releases of the SMTP mailer module for Drupal 7 (starting with 7.x-1.4) that effectively broke the functionality for a while, so I decided not to implement those same changes in the Backdrop version to keep our module in a usable state. 

Since then, the Drupal 7 version of SMTP has been fixed, so it might be worthwhile to review all the commits since 1.3 and see which are worth pulling over into the Backdrop version. Let's use this issue as a meta to track the changes we want to include.

**Comment by herbdool** [comment]
My PR (above) brings it to 1.7. In my tests it seems to be working fine. Plus we've got the Drupal version working on client sites with no trouble.

**Comment by jenlampton** [comment]
Ah, you're 2 steps ahead of me! :)

**Comment by herbdool** [comment]
Yup! Though I forgot to run the tests so I can fix those up first.

**Comment by herbdool** [comment]
humph. I took a look at the test. Turns out it relies on Maillog which would need to be ported. I might port it at any rate but means a delay. However, if we test it by hand it's probably just as good at least for the initial upgrade.

**Comment by herbdool** [comment]
Alright, SMTP tests are passing! I ported Maillog so I could run the tests and I'll upload Maillog to github soon as well.

**Comment by jenlampton** [comment]
you're on 🔥

**Comment by herbdool** [comment]
I've confirmed all the commits you identified above are in the PR.

**Comment by jenlampton** [comment]
I've merged in the PR. I'd like to leave it for at least a week before making a release, so others (mostly myself) can test it in the wild.

**Comment by jenlampton** [comment]
Thanks @herbdool for all your work on this!

**Comment by Graham-72** [comment]
I am doing some testing and so far have found no problems with this SMTP module but I have found and fixed a bug in Mailsystem module!

**Comment by herbdool** [comment]
@Graham-72 can you report the bug if you haven't already?

**Comment by jenlampton** [comment]
Closing as a new release will contain these changes. 🎉
