### ISSUE TITLE
Cross-port 7.x-1.8..7.x-1.9 or mark as NA

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/smtp#31]
Lots of important changes happened in the 7.x-1.x branch, that should be considered here.

- [x] #34 | [a78a194](https://cgit.drupalcode.org/smtp/commit/?id=a78a194ac3f621675bfb9e597ce7fe49de4423cb) | [Issue #3332455 by joseph.olstad: PHP 8.2 compatibility]
- [x] #27 | [05e04d4](https://cgit.drupalcode.org/smtp/commit/?id=05e04d4434d6ea02d976d34bb9a61ff9b51684cf) | [Issue #3009090 by u_tiwari, ravikk-drupal, mohangathala, solideogloria, Alina Basarabeanu, DamienMcKenna, Chris Matthews, Dru18, Krzysztof Domański: Remove code which contains deprecated function set_magic_quotes_runtime and ini directive 'magic_quotes_runtime']
- [x] #34 | [92199d0](https://cgit.drupalcode.org/smtp/commit/?id=92199d0e9d2809237646a8c8da1c6a5e5ac07d33) | [Issue #3050130 by shital.mahajan, ravikk-drupal, nipany, DamienMcKenna, Alina Basarabeanu:  INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4]
- [ ] #29 | [d748cca](https://cgit.drupalcode.org/smtp/commit/?id=d748ccacdd3b6150491ce276f788bd19b643f235) | [Issue #2986490 by das-peter, rivimey, jedihe, wundo, tonytheferg, DamienMcKenna: Re-Add MimeMail Integration]
- [ ] #29 | [9088d6a](https://cgit.drupalcode.org/smtp/commit/?id=9088d6ab9c9ad6b0534716ca2cc732d627e71979) | [Issue #1442514 by mmaldonado, killua99, DamienMcKenna, tobiasb, mavimo, SkyBuzz, tetter36, uberhacker, james.williams, moonberry, wundo, BD3, chrbak, Johan den Hollander, jurgenhaas, kolafson, cgdrupalkwk, MarcusOaten, felixvang, gabrielu, dandaman, AgentSeo, HansKuiters, Chris Matthews, bdeleasa, rasmusknabe@gmail.com, sam-elayyoub, robcarr, rreiss, lavisrap, Allerby, truman_ru, jayroberts, ann b, Sam152: Sending attachments using modules smtp and mimemail]
- [x] #41
